---
- name: Webserver Configuration
  hosts: "{{ app_host }}"
  gather_facts: "{{ facts }}"
  become: yes
  vars_files:
    - ../variables/webserver_vars.yaml
  tasks:
    - name: Ping
      ping:

    - name: Install Packages
      dnf:
        name: "{{ webserver_packages }}"
        state: latest

    - name: Download Wordpress and Unarchive Wordpress
      unarchive: 
        src: http://wordpress.org/latest.tar.gz
        dest: /tmp/
        remote_src: yes
      #notify: Copy Wordpress to /var/www/html

    - name: start and enabled httpd 
      systemd:
        name: httpd
        state: started
        enabled: yes
  
    - name: Copy everything from wordpress to /var/www/html  
      copy:
        dest: /var/www/html/
        remote_src: yes
        src: /tmp/wordpress/
        owner: apache
        group: apache
      notify: Restart apache
  
  handlers:
    - name: Restart apache
      systemd:
        name: httpd
        state: restarted


      
      