---
- name: Add ansible user
  hosts: all
  gather_facts: yes
  tasks:
    - name: Add ansible user, copy ssh-key
      block:
        - name: Add ansible user
          user:
            name: ansible
            uid: 2000
            group: wheel
        - name: Add SSH Key
          authorized_key:
            user: ansible
            state: present
            key: "{{ lookup('file','/home/ansible/.ssh/id_rsa.pub') }}"
      when: ansible_distribution == "CentOS"

    - name: Add ansible user, copy ssh-key to Ubuntu Server
      block: 
        - name: Add ansible user
          user:
            name: ansible
            uid: 2000
            group: sudo
        - name: Add SSH Key
          authorized_key:
            user: ansible
            state: present
            key: "{{ lookup ('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      when: ansible_distribution == "Ubuntu"